#!/usr/bin/env python
# Because fuck you bash

import os

# Reset the db, resync it, load initial fixtures
os.system('echo "yes" | python manage.py reset wikinotes')
os.system('python manage.py syncdb')
os.system('python manage.py loaddata faculties departments courses')
print 'Done.'
