from django.shortcuts import render_to_response, get_object_or_404
from wiki.models.courses import Course, CourseSemester
from utils import page_types as types
from django.template import RequestContext
from wiki.models.pages import Page
from django.http import Http404

def show(request, department, number, page_type, term, year, slug):
	course = get_object_or_404(Course, department=department, number=int(number))
	course_sem = get_object_or_404(CourseSemester, course=course, term=term, year=year)
	page = get_object_or_404(Page, course_sem=course_sem, page_type=page_type, slug=slug)
	page_type_obj = types[page_type]
	data = {
		'course': course,
		'page': page,
		'sections': page.load_sections(page_type_obj),
		'show_template': page_type_obj.get_show_template(),
		'edit_url': page.get_url() + '/edit',
	}
	return render_to_response("pages/show.html", data, context_instance=RequestContext(request))

def edit(request, department, number, page_type, term, year, slug):
	course = get_object_or_404(Course, department=department, number=int(number))
	course_sem = get_object_or_404(CourseSemester, course=course, term=term, year=year)
	page = get_object_or_404(Page, course_sem=course_sem, page_type=page_type, slug=slug)
	page_type_obj = types[page_type]
	
	data = {
		'course': course,
		'page': page, # to distinguish it from whatever
		'field_templates': page_type_obj.get_field_templates(),
		'num_sections': range(1, 11),
		'help_template': page_type_obj.get_help_template(),
		'sections': page.load_sections(page_type_obj),
		'num_sections': range(1, 11) if page.num_sections < 11 else range(1, page.num_sections + 1), # check on this later
		'terms': ['winter', 'summer', 'fall'], # fix this later
		'years': range(2011, 1999, -1),
	}
	return render_to_response("pages/edit.html", data, context_instance=RequestContext(request))

def create(request, department, number, page_type):
	course = get_object_or_404(Course, department=department, number=int(number))

	if page_type not in types:
		raise Http404
	else:
		obj = types[page_type]
		if request.method == 'POST':
			# Create the page
			num_sections = request.POST['num_sections']
			term = request.POST['term']
			year = request.POST['year']
			try:
				course_sem = CourseSemester.objects.get(term=term, year=year, course=course)
			except CourseSemester.DoesNotExist:
				course_sem = CourseSemester(term=term, year=year, course=course)
				course_sem.save()

			# The title and subject are generated by the PageType object, in kwargs
			kwargs = obj.get_kwargs(request.POST)
			new_page = Page(course_sem=course_sem, num_sections=num_sections, page_type=page_type, **kwargs)
			new_page.save()
			new_page.save_sections(request.POST)
			data = {
				'course': course,
			}
			# Get the keyword arguments from the page type method
			if new_page:
				data['new_page'] = new_page
				return render_to_response("pages/success.html", data, context_instance=RequestContext(request))
			else:
				return render_to_response("pages/error.html", data, context_instance=RequestContext(request))
		else:
			data = {
				'course': course,
				'page_type': obj,
				'form_template': obj.get_form_template(),
				'help_template': obj.get_help_template(),
				'field_templates': obj.get_field_templates(),
				'terms': ['winter', 'summer', 'fall'], # fix this later
				'years': range(2011, 1999, -1),
				'num_sections': range(1, 11), # for people without javascript DON'T DELETE THIS UNLESS YOU HAVE ANOTHER SOLUTION FOR A FALLBACK
			}
			return render_to_response("pages/create.html", data, context_instance=RequestContext(request))
